[book]
authors = ["TurtleSmoke"]
description = "Solution of Project Euler problems"
language = "en"
multilingual = false
src = "mdbook_src"
title = "Project Euler"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/TurtleSmoke/project-euler"
site-url = "https://turtlesmoke.dev/project-euler"
mathjax-support = true
default-theme = "navy"
preferred-dark-theme = "navy"

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
limit-result = 20
use-boolean-and = true
