[book]
authors = ["TurtleSmoke"]
language = "en"
multilingual = false
src = "mdbook_src"
title = "Project Euler"

[output.html]
git-repository-url = "https://github.com/TurtleSmoke/Project-Euler"
site-url = "https://turtlesmoke.github.io/Project-Euler"
mathjax-support = true

