#!/bin/bash

rm -rf problems/problem_"$1"
rm -rf mdbook_src/problems/problem_"$1"

last_lines="$(tail -n 2 mdbook_src/SUMMARY.md)"

# Only remove lines generated by `generate_example.sh`
head -n -2 mdbook_src/SUMMARY.md > tmp && mv tmp mdbook_src/SUMMARY.md
echo "$last_lines" >> mdbook_src/SUMMARY.md
